const hoodies = [
  {
    category: "hoodie",
    color: "#1C1C1C",
    desc: "Siyah kapüşonlu, rahat kesim hoodie.",
    price: 59.99,
    title: "Siyah Hoodie",
    img_url: "https://example.com/images/hoodie-black.jpg",
  },
  {
    category: "hoodie",
    color: "#FF6347",
    desc: "Kırmızı kapüşonlu, sıcak tutan hoodie.",
    price: 64.99,
    title: "Kırmızı Hoodie",
    img_url: "https://example.com/images/hoodie-red.jpg",
  },
  {
    category: "hoodie",
    color: "#4682B4",
    desc: "Mavi, su geçirmez kapüşonlu hoodie.",
    price: 69.99,
    title: "Mavi Su Geçirmez Hoodie",
    img_url: "https://example.com/images/hoodie-blue.jpg",
  },
  {
    category: "hoodie",
    color: "#FFD700",
    desc: "Sarı, yumuşak kapüşonlu hoodie.",
    price: 55.99,
    title: "Sarı Yumuşak Hoodie",
    img_url: "https://example.com/images/hoodie-yellow.jpg",
  },
  {
    category: "hoodie",
    color: "#FF4500",
    price: 61.99,
    img_url: "https://example.com/images/hoodie-orange.jpg",
  },
  {
    category: "hoodie",
    color: "#8A2BE2",
    desc: "Mor kapüşonlu, yumuşak dokunuş hoodie.",
    price: 59.49,
    title: "Mor Kapüşonlu Hoodie",
    img_url: "https://example.com/images/hoodie-purple.jpg",
  },
  {
    category: "hoodie",
    color: "#7FFF00",
    desc: "Yeşil sportif kapüşonlu hoodie.",
    price: 63.99,
    title: "Yeşil Sportif Hoodie",
    img_url: "https://example.com/images/hoodie-green.jpg",
  },
  {
    category: "hoodie",
    color: "#FF1493",
    desc: "Pembe kapüşonlu, kadınlar için özel tasarım hoodie.",
    price: 62.99,
    title: "Pembe Kadın Hoodie",
    img_url: "https://example.com/images/hoodie-pink.jpg",
  },
  {
    category: "hoodie",
    color: "#D2691E",
    desc: "Kahverengi kapüşonlu, rahat kesim hoodie.",
    price: 58.49,
    title: "Kahverengi Kapüşonlu Hoodie",
    img_url: "https://example.com/images/hoodie-brown.jpg",
  },
  {
    category: "hoodie",
    color: "#DC143C",
    desc: "Koyu kırmızı kapüşonlu hoodie, pamuklu.",
    price: 66.99,
    title: "Koyu Kırmızı Hoodie",
    img_url: "https://example.com/images/hoodie-darkred.jpg",
  },
  {
    category: "hoodie",
    color: "#2E8B57",
    desc: "Orman yeşili kapüşonlu, doğa dostu hoodie.",
    price: 60.99,
    title: "Orman Yeşili Hoodie",
    img_url: "https://example.com/images/hoodie-forestgreen.jpg",
  },
  {
    category: "hoodie",
    color: "#000080",
    desc: "Lacivert kapüşonlu, günlük giyim için ideal hoodie.",
    price: 59.99,
    title: "Lacivert Günlük Hoodie",
    img_url: "https://example.com/images/hoodie-navy.jpg",
  },
  {
    category: "hoodie",
    color: "#F08080",
    desc: "Açık kırmızı kapüşonlu, rahat ve şık hoodie.",
    price: 64.49,
    title: "Açık Kırmızı Hoodie",
    img_url: "https://example.com/images/hoodie-lightred.jpg",
  },
];

const sweatpants = [
  {
    category: "sweatpants",
    color: "#808080",
    desc: "Gri renkli rahat eşofman altı.",
    price: 35.99,
    title: "Gri Rahat Eşofman",
    img_url: "https://example.com/images/sweatpants-grey.jpg",
  },
  {
    category: "sweatpants",
    color: "#000000",
    desc: "Siyah düz kesim eşofman altı.",
    price: 37.99,
    title: "Siyah Düz Kesim Eşofman",
    img_url: "https://example.com/images/sweatpants-black.jpg",
  },
  {
    category: "sweatpants",
    color: "#FF4500",
    desc: "Turuncu sportif eşofman altı.",
    price: 40.99,
    title: "Turuncu Sportif Eşofman",
    img_url: "https://example.com/images/sweatpants-orange.jpg",
  },
  {
    category: "sweatpants",
    color: "#228B22",
    desc: "Yeşil bol kesim eşofman altı.",
    price: 36.99,
    title: "Yeşil Bol Kesim Eşofman",
    img_url: "https://example.com/images/sweatpants-green.jpg",
  },
  {
    category: "sweatpants",
    color: "#0000FF",
    desc: "Mavi spor eşofman altı.",
    price: 38.99,
    title: "Mavi Spor Eşofman",
    img_url: "https://example.com/images/sweatpants-blue.jpg",
  },
  {
    category: "sweatpants",
    color: "#B22222",
    desc: "Kırmızı renkli, rahat eşofman altı.",
    price: 39.99,
    title: "Kırmızı Eşofman",
    img_url: "https://example.com/images/sweatpants-red.jpg",
  },
  {
    category: "sweatpants",
    color: "#2F4F4F",
    desc: "Koyu gri eşofman altı, rahat kesim.",
    price: 41.99,
    title: "Koyu Gri Eşofman",
    img_url: "https://example.com/images/sweatpants-darkgrey.jpg",
  },
  {
    category: "sweatpants",
    color: "#4682B4",
    desc: "Açık mavi, rahat kesim eşofman altı.",
    price: 34.99,
    title: "Açık Mavi Eşofman",
    img_url: "https://example.com/images/sweatpants-lightblue.jpg",
  },
  {
    category: "sweatpants",
    color: "#FFD700",
    desc: "Sarı sportif eşofman altı.",
    price: 37.49,
    title: "Sarı Sportif Eşofman",
    img_url: "https://example.com/images/sweatpants-yellow.jpg",
  },
  {
    category: "sweatpants",
    color: "#F4A460",
    desc: "Krem rengi, pamuklu eşofman altı.",
    price: 39.49,
    title: "Krem Rengi Eşofman",
    img_url: "https://example.com/images/sweatpants-cream.jpg",
  },
  {
    category: "sweatpants",
    color: "#FFC0CB",
    desc: "Pembe sportif kesim eşofman altı.",
    price: 36.99,
    title: "Pembe Eşofman",
    img_url: "https://example.com/images/sweatpants-pink.jpg",
  },
];

const tshirts = [
  {
    category: "tshirt",
    color: "#34A853",
    desc: "Yüksek kaliteli, nefes alabilir pamuklu yeşil tişört.",
    price: 19.99,
    title: "Yeşil Pamuklu Tişört",
    img_url: "https://example.com/images/tshirt-green.jpg",
  },
  {
    category: "tshirt",
    color: "#FF0000",
    desc: "Pamuklu, kırmızı rahat kesim tişört.",
    price: 17.99,
    title: "Kırmızı Pamuklu Tişört",
    img_url: "https://example.com/images/tshirt-red.jpg",
  },
  {
    category: "tshirt",
    color: "#000000",
    desc: "Siyah, günlük kullanım için ideal tişört.",
    price: 18.49,
    title: "Siyah Günlük Tişört",
    img_url: "https://example.com/images/tshirt-black.jpg",
  },
  {
    category: "tshirt",
    color: "#1E90FF",
    desc: "Mavi, nefes alabilir tişört, sporcular için uygun.",
    price: 20.99,
    title: "Mavi Spor Tişört",
    img_url: "https://example.com/images/tshirt-blue.jpg",
  },
  {
    category: "tshirt",
    color: "#FFFF00",
    desc: "Sarı, hafif ve şık tişört.",
    price: 18.99,
    title: "Sarı Şık Tişört",
    img_url: "https://example.com/images/tshirt-yellow.jpg",
  },
  {
    category: "tshirt",
    color: "#8A2BE2",
    price: 21.49,
    img_url: "https://example.com/images/tshirt-purple.jpg",
  },
  {
    category: "tshirt",
    color: "#FFC0CB",
    desc: "Pembe, kadınlar için özel tasarım tişört.",
    price: 19.49,
    title: "Pembe Kadın Tişört",
    img_url: "https://example.com/images/tshirt-pink.jpg",
  },
  {
    category: "tshirt",
    color: "#2F4F4F",
    desc: "Koyu gri, rahat kesim tişört.",
    price: 17.49,
    title: "Koyu Gri Tişört",
    img_url: "https://example.com/images/tshirt-darkgrey.jpg",
  },
  {
    category: "tshirt",
    color: "#FF4500",
    desc: "Turuncu, günlük kullanım için şık tişört.",
    price: 18.99,
    title: "Turuncu Günlük Tişört",
    img_url: "https://example.com/images/tshirt-orange.jpg",
  },
  {
    category: "tshirt",
    color: "#4B0082",
    desc: "Lacivert, sportif kesim tişört.",
    price: 20.99,
    title: "Lacivert Sportif Tişört",
    img_url: "https://example.com/images/tshirt-indigo.jpg",
  },
  {
    category: "tshirt",
    color: "#FA8072",
    desc: "Somon rengi, hafif dokunuşlu tişört.",
    price: 19.49,
    title: "Somon Rengi Tişört",
    img_url: "https://example.com/images/tshirt-salmon.jpg",
  },
  {
    category: "tshirt",
    color: "#F08080",
    desc: "Açık kırmızı, pamuklu ve nefes alabilir tişört.",
    price: 19.99,
    title: "Açık Kırmızı Pamuklu Tişört",
    img_url: "https://example.com/images/tshirt-lightred.jpg",
  },
  {
    category: "tshirt",
    color: "#A52A2A",
    desc: "Kahverengi klasik tişört, günlük kullanım.",
    price: 21.49,
    title: "Kahverengi Klasik Tişört",
    img_url: "https://example.com/images/tshirt-brown.jpg",
  },
  {
    category: "tshirt",
    color: "#87CEEB",
    desc: "Açık mavi, hafif dokulu tişört.",
    price: 17.99,
    title: "Açık Mavi Hafif Tişört",
    img_url: "https://example.com/images/tshirt-lightblue.jpg",
  },
  {
    category: "tshirt",
    color: "#008080",
    desc: "Turkuaz, nefes alabilir yazlık tişört.",
    price: 18.49,
    title: "Turkuaz Yazlık Tişört",
    img_url: "https://example.com/images/tshirt-teal.jpg",
  },
  {
    category: "tshirt",
    color: "#FF1493",
    desc: "Fuşya, kadınlar için yazlık tişört.",
    price: 19.99,
    title: "Fuşya Kadın Tişört",
    img_url: "https://example.com/images/tshirt-fuchsia.jpg",
  },
  {
    category: "tshirt",
    color: "#708090",
    desc: "Gri mavi karışımı, hafif ve rahat tişört.",
    price: 20.49,
    title: "Gri Mavi Karışımı Tişört",
    img_url: "https://example.com/images/tshirt-slateblue.jpg",
  },
  {
    category: "tshirt",
    color: "#CD853F",
    desc: "Koyu bej, günlük kullanım için ideal tişört.",
    price: 18.99,
    title: "Koyu Bej Günlük Tişört",
    img_url: "https://example.com/images/tshirt-darkbeige.jpg",
  },
  {
    category: "tshirt",
    color: "#B8860B",
    desc: "Altın sarısı, modern kesim tişört.",
    price: 19.49,
    title: "Altın Sarısı Modern Tişört",
    img_url: "https://example.com/images/tshirt-gold.jpg",
  },
  {
    category: "tshirt",
    color: "#DAA520",
    desc: "Hardal sarısı, rahat ve stil sahibi tişört.",
    price: 19.99,
    title: "Hardal Sarısı Tişört",
    img_url: "https://example.com/images/tshirt-mustard.jpg",
  },
  {
    category: "tshirt",
    color: "#FFDEAD",
    desc: "Açık bej, sade ve şık tişört.",
    price: 17.99,
    title: "Açık Bej Şık Tişört",
    img_url: "https://example.com/images/tshirt-lightbeige.jpg",
  },
  {
    category: "tshirt",
    color: "#DEB887",
    desc: "Açık kahve, yumuşak dokunuşlu tişört.",
    price: 19.49,
    title: "Açık Kahve Tişört",
    img_url: "https://example.com/images/tshirt-lightbrown.jpg",
  },
  {
    category: "tshirt",
    color: "#8B4513",
    desc: "Kestane rengi, rahat kesim tişört.",
    price: 18.99,
    title: "Kestane Rengi Tişört",
    img_url: "https://example.com/images/tshirt-chestnut.jpg",
  },
];

export { hoodies, tshirts, sweatpants };
