export const products = [
  {
    category: "T-shirt",
    color: "#34A853",
    size: "M",
    desc: "Yüksek kaliteli, nefes alabilir pamuklu yeşil tişört.",
    price: 19.99,
    title: "Yeşil Pamuklu Tişört",
    img_url: "https://example.com/images/tshirt-green.jpg",
  },
  {
    category: "Sweatpants",
    color: "#4285F4",
    size: "L",
    desc: "Rahat ve şık mavi eşofman altı.",
    price: 29.99,
    title: "Mavi Eşofman Altı",
    img_url: "https://example.com/images/sweatpants-blue.jpg",
  },
  {
    category: "Sweater",
    color: "#EA4335",
    size: "S",
    desc: "Yumuşak ve sıcak kırmızı süveter.",
    price: 39.99,
    title: "Kırmızı Süveter",
    img_url: "https://example.com/images/sweater-red.jpg",
  },
  {
    category: "T-shirt",
    color: "#FFB74D",
    size: "XL",
    desc: "Rahat ve hafif turuncu tişört.",
    price: 17.99,
    title: "Turuncu Tişört",
    img_url: "https://example.com/images/tshirt-orange.jpg",
  },
  {
    category: "Sweatpants",
    color: "#F4E5E5",
    size: "2XL",
    desc: "Geniş kesim beyaz eşofman altı.",
    price: 31.99,
    title: "Beyaz Eşofman Altı",
    img_url: "https://example.com/images/sweatpants-white.jpg",
  },
  {
    category: "Sweater",
    color: "#FFC0CB",
    size: "3XL",
    desc: "Yumuşak pembe süveter, soğuk günler için ideal.",
    price: 44.99,
    title: "Pembe Süveter",
    img_url: "https://example.com/images/sweater-pink.jpg",
  },
];
